### PR TITLE
Create autoplay.md

### PR DESCRIPTION
**Pull request by sphh**
Hi, I wrote (and uploaded this new extension to PyPi), because I hated it from the beginning, that after switching on my Raspberry running Mopidy I had to start the computer, start the browser and head to Mopidy to start playing my favourite webradio.

I would appreciate, if you could add it to your list of extensions (or give me some comments about the implementation ;-) ). Thanks.

### CODE REVIEW

**Comment by trygveaa** [comment]
Have you seen the [core/restore_state](https://docs.mopidy.com/en/latest/config/#confval-core-restore_state) configuration option?

**Comment by sphh** [comment]
No, I missed that completely!!! This is exactly the default behaviour, so I will mention it in the docs.

But I believe that Mopidy-Autoplay can do more: You can override some of this default behaviour, e.g. set the mute state or the volume. You could also specify a default track.

* Does [core/restore_state](https://docs.mopidy.com/en/latest/config/#confval-core-restore_state) also restore the 4 tracklist options?
* Is it possible to set the `core/restore_state` from an extension? That would reduce my code just to the cases, where the user wants to override some features.

**Comment by kingosticks** [comment]
And how do you handle trying to play from backends that have not finished initialising? For example, Mopidy-Spotify will login asynchronously and won't be ready for playback immediately. I guess it works fine for local and streams but I think you'll run into problems with others. And I don't believe we have a way to handle this in Mopidy today, so this is more of a warning for something to look out for.

**Comment by kingosticks** [comment]
Yes, it restores all tracklist options, see https://github.com/mopidy/mopidy/blob/8b2c12412e8ab3b00e1e27a585cde59e9f914bc4/mopidy/core/tracklist.py#L616

No, it's not part of the Core API

**Comment by sphh** [comment]
Assuming I want to use the built-in `core/restore_state = true` feature, I would somehow need to enable this configuration. One way would require manual intervention by the user herself: She must add it to her configuration file by hand.

If that could be automated, it would be great. One idea is to set `core/restore_state` to `true` in my extension's `ext.conf`? E.g. `mopidy-autoplay/ext.conf`:
```ini
[core]
restore_state = true

[autoplay]
enabled = true
```
Would that work?

But now the question arises:
* Which configuration would take precedence, if `core/restore_state` is found both in my extension's `ext.conf` and in the main configuration file?

Regarding the case, that some backends have not finished initialising: Honestly, I did not think about it, because I was not aware of it (and I don't use Mopidy-Spotify). Thanks for pointing this out. I guess, I have to add a warning to the documentation …

**Comment by sphh** [comment]
I updated the [README.rst](https://github.com/sphh/mopidy-autoplay/blob/hg/README.rst), which now mentions the `core/restore_state = true` configuration option and that this might option might be enough for many users.

Other changes:
- Mention, that any URI understood by Mopidy can be used in the `autoplay/tracklist.uris` configuration option.
- Add ability to load playlists given in the `autoplay/tracklist.uris` configuration option.
- Add special URI prefix `match:`, which at this moment can be used together with the `File` extension to load files using glob patterns, e.g. `match:file:///usr/share/sounds/alsa/*.wav` (that's the only `match:` currently implemented, but it might be possible to extend this to other URIs in future).
- Updated the README to explain one way, how to get the URI.

**Comment by kingosticks** [comment]
> And how do you handle trying to play from backends that have not finished initialising? For example, Mopidy-Spotify will login asynchronously and won't be ready for playback immediately. I guess it works fine for local and streams but I think you'll run into problems with others. 

Just for reference, we saw this problem in the wild at https://discourse.mopidy.com/t/restore-state-not-working-for-dlna-extension/4358

**Comment by sphh** [comment]
Honestly, I don't handle it at all. By reading the link, `core/restore_state = true` has the same problem. Has this been resolved?? And if yes, how was this done?

**Comment by kingosticks** [comment]
It's still unresolved. I didn't much like any of the [suggestions I made](https://discourse.mopidy.com/t/restore-state-not-working-for-dlna-extension/4358/8) in that thread. I'm not suggesting you need to solve that issue but at least you know the problem does exist in case someone reports it.

I like your thorough README and that you've mentioned the other similar projects. I have a question: do you need to ensure `core/restore_state = false` for your extension to work? What happens if it's set `true`?

Also, does your glob functionality access files outside of the configured media folders? We've been quite careful to limit/disallow that for our Local and File extensions.

What happens to URIs that contain characters that are reserved for config files? e.g. '#' and ';' ?

**Comment by sphh** [comment]
Good point. I will mention this problem in the README.

Regarding your questions:

1. Also a good point. I have not tested it. I'll do and mention any incompatibility in the README.

2. Yes, it does (as you have seen in my example) and it does work. Is this something to prevent? At the moment, the `File` extension accepts such URIs.

3. As long as Mopidy's config parser parses the whole line into a list, they should work. If such URIs are not parsed correctly, there will be a problem, since I rely on Mopidy's config parser. Can these characters be escaped? Then I have to mention this in the README.

**Comment by kingosticks** [comment]
Hmm I thought File blocked that access. OK, maybe not.

Normally they'd be quoted but you've explicitly said not do that in your readme.

**Comment by sphh** [comment]
If I quote them, e.g.
```ini
[autoplay]
tracklist.uris = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p", "file:///usr/share/sounds/alsa/Noise.wav"
```
the quotes are preserved by the config parser and I get the following list:
```python3
['"http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p"', '"file:///usr/share/sounds/alsa/Noise.wav"']
```
Is this the default behaviour of Mopidy's config parser? If yes, I have to strip the quotation marks manually.

I just tried it with the following entry:
```ini
[autoplay]
tracklist.uris = http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p#, file:///usr/sh;are/sounds/alsa/Noise.wav
```
and Mopidy's config parser returns
```python3
['http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p#', 'file:///usr/sh;are/sounds/alsa/Noise.wav']
```
which looks perfectly ok to me.

**Comment by kingosticks** [comment]
The behaviour did change slightly when we moved to Python 3. I'm not at a machine to test anything but if it looks fine then please ignore me!

**Comment by sphh** [comment]
The only problematic case I can imagine at the moment, is a comma `,` in the URI …

But I have another question, which puzzles me:
In this line https://github.com/sphh/mopidy-autoplay/blob/f67481dd32f8fa3120d8cd28b96624afb5982828/mopidy_autoplay/frontend.py#L202, I start playing from the queue/tracklist at the given index. Sometimes it plays just this track and sometimes it plays all the tracks in the tracklist. I could not figure out any pattern. What would be the right way, to play all tracks in the tracklist?

**Comment by kingosticks** [comment]
Are you sure single mode is not enabled?

**Comment by sphh** [comment]
Yes. I now investigated a bit and noticed the following behaviour:

1. I load all `.wav` files from `/usr/share/sounds/alsa/` and then an internet stream.
2. Mopidy starts with single mode disabled.
3. When the GUI of my choice (`mopidy_musicbox_webclient`) can connect to Mopidy again, it displays the queue correctly with the second file selected ready to play. It looks, like the first file was played (but I could not hear it) and then Mopidy stopped playing (similar to having single mode enabled, but which is not). If I now press the Play button, Mopidy plays the rest of the queue, progressing from one file to the next.

Could this be a timing problem, similar to that of backends needing long to initialize?

These are the debug messages, after my extensions loads the tracklist and starts playing (I manually inserted the calls into the log):
```log
#
# self.core.tracklist.add(uris=uris)
Oct 17 12:55:32 mopidy mopidy[8876]: DEBUG    [Core-8] mopidy.core.tracklist Triggering event: tracklist_changed()
Oct 17 12:55:32 mopidy mopidy[8876]: DEBUG    [Core-8] mopidy.listener Sending tracklist_changed to CoreListener: {}
Oct 17 12:55:32 mopidy mopidy[8876]: DEBUG    [FileBackend-5] mopidy.file.library Looking up file URI: file:///usr/share/sounds/alsa/Noise.wav
Oct 17 12:55:33 mopidy mopidy[8876]: DEBUG    [FileBackend-5] mopidy.file.library Looking up file URI: file:///usr/share/sounds/alsa/Front_Center.wav
Oct 17 12:55:33 mopidy mopidy[8876]: DEBUG    [FileBackend-5] mopidy.file.library Looking up file URI: file:///usr/share/sounds/alsa/Side_Left.wav
Oct 17 12:55:33 mopidy mopidy[8876]: DEBUG    [FileBackend-5] mopidy.file.library Looking up file URI: file:///usr/share/sounds/alsa/Side_Right.wav
Oct 17 12:55:34 mopidy mopidy[8876]: DEBUG    [FileBackend-5] mopidy.file.library Looking up file URI: file:///usr/share/sounds/alsa/Rear_Center.wav
Oct 17 12:55:34 mopidy mopidy[8876]: DEBUG    [FileBackend-5] mopidy.file.library Looking up file URI: file:///usr/share/sounds/alsa/Front_Left.wav
Oct 17 12:55:34 mopidy mopidy[8876]: DEBUG    [FileBackend-5] mopidy.file.library Looking up file URI: file:///usr/share/sounds/alsa/Front_Right.wav
Oct 17 12:55:34 mopidy mopidy[8876]: DEBUG    [FileBackend-5] mopidy.file.library Looking up file URI: file:///usr/share/sounds/alsa/Rear_Left.wav
Oct 17 12:55:34 mopidy mopidy[8876]: DEBUG    [FileBackend-5] mopidy.file.library Looking up file URI: file:///usr/share/sounds/alsa/Rear_Right.wav
Oct 17 12:55:34 mopidy mopidy[8876]: DEBUG    [Core-8] mopidy.core.tracklist Triggering event: tracklist_changed()
Oct 17 12:55:34 mopidy mopidy[8876]: DEBUG    [Core-8] mopidy.listener Sending tracklist_changed to CoreListener: {}
#
# self.core.playback.play(tlid=tlid)
Oct 17 12:55:34 mopidy mopidy[8876]: WARNING  [AutoplayFrontend-10] mopidy_autoplay.frontend ****** playing
Oct 17 12:55:35 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.gst Changing state to GST_STATE_READY: result=GST_STATE_CHANGE_SUCCESS
Oct 17 12:55:35 mopidy mopidy[8876]: DEBUG    [MainThread] mopidy.audio.gst Got STATE_CHANGED bus message: old=GST_STATE_NULL new=GST_STATE_READY pending=GST_STATE_VOID_PENDING
Oct 17 12:55:35 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.gst Got source-setup signal: element=GstFileSrc
Oct 17 12:55:35 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.gst Changing state to GST_STATE_PLAYING: result=GST_STATE_CHANGE_ASYNC
Oct 17 12:55:35 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.gst Changing state to GST_STATE_READY: result=GST_STATE_CHANGE_SUCCESS
Oct 17 12:55:35 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.gst Got source-setup signal: element=GstFileSrc
Oct 17 12:55:35 mopidy mopidy[8876]: DEBUG    [MainThread] mopidy.audio.gst Got STATE_CHANGED bus message: old=GST_STATE_READY new=GST_STATE_READY pending=GST_STATE_VOID_PENDING
Oct 17 12:55:35 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.gst Changing state to GST_STATE_PLAYING: result=GST_STATE_CHANGE_ASYNC
Oct 17 12:55:35 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.gst Changing state to GST_STATE_READY: result=GST_STATE_CHANGE_SUCCESS
Oct 17 12:55:35 mopidy mopidy[8876]: DEBUG    [MainThread] mopidy.audio.gst Got STATE_CHANGED bus message: old=GST_STATE_READY new=GST_STATE_READY pending=GST_STATE_VOID_PENDING
```

and this after I press the Play button in the GUI, when Mopidy plays the rest of the tracklist, progressing to the next file/stream:
```log
Oct 17 12:59:12 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.actor Position query failed
Oct 17 12:59:12 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.gst Changing state to GST_STATE_READY: result=GST_STATE_CHANGE_SUCCESS
Oct 17 12:59:12 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.gst Got source-setup signal: element=GstFileSrc
Oct 17 12:59:12 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.gst Changing state to GST_STATE_PLAYING: result=GST_STATE_CHANGE_ASYNC
Oct 17 12:59:12 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.actor Position query failed
Oct 17 12:59:12 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.actor Position query failed
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Audio-1] mopidy.audio.actor Position query failed
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [MainThread] mopidy.audio.gst Got STREAM_START bus message
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [MainThread] mopidy.audio.actor Audio event: stream_changed(uri='file:///usr/share/sounds/alsa/Front_Center.wav')
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [MainThread] mopidy.listener Sending stream_changed to AudioListener: {'uri': 'file:///usr/share/sounds/alsa/Front_Center.wav'}
Oct 17 12:59:13 mopidy kernel: usb 1-1.5.4: current rate 8436480 is different from the runtime rate 48000
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Core-8] mopidy.core.playback Triggering track playback ended event
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Core-8] mopidy.listener Sending track_playback_ended to CoreListener: {'tl_track': TlTrack(tlid=2, track=Track(bitrate=768000, length=1428, name='Front_Center.wav', uri='file:///usr/share/sounds/alsa/Front_Center.wav')), 'time_position': 0}
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Dummy-451] mopidy.audio.gst Got about-to-finish event.
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Dummy-450] mopidy.audio.gst Got SEGMENT pad event: rate=1.0 format=time start=0 stop=18446744073709551615 position=0
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Dummy-450] mopidy.audio.actor Audio event: position_changed(position=0)
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Core-8] mopidy.core.playback Changing state: stopped -> playing
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Dummy-451] mopidy.audio.actor Running about-to-finish callback.
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Dummy-450] mopidy.listener Sending position_changed to AudioListener: {'position': 0}
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Core-8] mopidy.core.playback Triggering playback state change event
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Core-8] mopidy.listener Sending playback_state_changed to CoreListener: {'old_state': 'stopped', 'new_state': 'playing'}
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Core-8] mopidy.core.playback Triggering track playback started event
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'container-format': ['WAV'], 'bitrate': [768000], 'audio-codec': ['Uncompressed 16-bit PCM audio']}
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [MainThread] mopidy.audio.actor Audio event: tags_changed(tags=['container-format', 'bitrate', 'audio-codec'])
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [MainThread] mopidy.listener Sending tags_changed to AudioListener: {'tags': ['container-format', 'bitrate', 'audio-codec']}
Oct 17 12:59:13 mopidy mopidy[8876]: DEBUG    [Core-8] mopidy.listener Sending track_playback_started to CoreListener: {'tl_track': TlTrack(tlid=2, track=Track(bitrate=768000, length=1428, name='Front_Center.wav', uri='file:///usr/share/sounds/alsa/Front_Center.wav'))}
```

**Comment by sphh** [comment]
I also do not understand the difference between using `PlaybackController.play|stop|pause|resume()` and `PlaybackController.set_state(PlaybackState.STOPPED|PLAYING|PAUSED)`. I just noticed, that setting only the state with `PlaybackController.set_state(PlaybackState.PLAYING)` does not start playing. I now tried a combination of
```python3
PlaybackController.play()
PlaybackController.set_state(PlaybackState.PLAYING)
```
which seems to work (for now).

**Comment by jodal** [comment]
IIRC you should never use `set_state()` directly. It is intended for use by other methods in the core layer and for the audio layer. The audio layer will set the state to `PLAYING` when GStreamer is actually playing.

**Comment by sphh** [comment]
Thanks for the explanation.

Shouldn't it then be called `_set_state()`? Or at least mention it in the documentation?

**Comment by kingosticks** [comment]
We already have a notice right at the top of https://docs.mopidy.com/en/latest/api/

**Comment by sphh** [comment]
Sorry, but that's what confused me: According to the two notices pointed out by you, it is perfectly feasible to use `PlaybackController.set_state()`, because it is mentioned in the documentation and does not start with an underscore.

Contrary to this, @jodal says (if I understand him correctly), that this method should never be used. That's what makes me wonder, if it would not be better to either remove this method from the documentation or rename it to have a leading underscore.

**Comment by kingosticks** [comment]
Sorry! You are absolutely right, I should have checked properly. @jodal that is our mistake having it listed there, isn't it?

**Comment by jodal** [comment]
I don't remember any specifics here, but we probably didn't prefix it with underscore because it is used by the audio layer, which is another Pykka actor. Underscored methods are not available through Pykka actor proxies.

I think the best we can do here is to document that the method is only intended for the audio layer.

I don't think there's any use case where you should use it from a frontend. We should do a search through frontends to see if any actually uses the method.

**Comment by sphh** [comment]
I just added comments regarding possible problems with `core/restore_state = true` and if backends are not initialized in time to the `README.rst` file. I also mentioned that it is currently possible to play any file from the filesystem with `file://`, but that this might change in future.

I also squashed one little bug.

Is there anything else missing for this extension to get included into the list of available extensions?

**Review by kingosticks — APPROVED** [review]

**Comment by sphh** [comment]
Thanks!!!

**Pull request merged**
