### PR TITLE
fixes #18

### LINKED ISSUE #18: Remove python2 extensions
At this point it is very unlikely that any of the remaining extensions will be ported. I've had a look at all py2 backends, (web-)frontends and mixers: none\* \*\* of them have had any activity in years and bug reports have gone ignored.
\* except pimusixbox/mopidy-websettings, which is at least responding to tickets
\*\* mopidy-subsonic suggests Prior99/mopidy-subidy as a replacement.

These extensions make navigating the extension directory harder/confusing and might lead new users to install an old version of mopidy.

I propose removing them from /ext/ and /ext/dists/. In the same go, we can then remove the cluttered "python 3" labels. If an extension were to still get ported, re-adding it will be easy.

I'd happily compile a PR if this gets accepted.

- [x] replace -subsonic with -subidy
- [x] purge py2-only extensions from /_ext
- [x] remove green 'python3' label; rename yellow one to 'prerelease'
- [x] on /ext/dists/, remove py3 column and add 'prerelease' label where applicable

### PR DESCRIPTION
**Pull request by girst**

### CODE REVIEW

**Comment by jodal** [comment]
Thanks :-)

**Comment by kingosticks** [comment]
I think this has resulted in the all the PyPI install instructions incorrectly using `python` instead of `python3`.

**Comment by girst** [comment]
On Tue, Mar 03, 2020 at 11:19:33AM -0800, Nick Steel wrote:
>I think this has resulted in the all the PyPI install instructions 
>incorrectly using `python` instead of `python3`.

you're right, sorry about that. I've grepped for other occurences of 
`py3` and that one was the last one.

opened a PR here: https://github.com/mopidy/website/pull/24

**Comment by kingosticks** [comment]
Cheers, I couldn't (reliably) grep the other files using github on my phone else I'd have just changed it!

**Pull request merged**
