### PR TITLE
✨ Add Mopidy-Apollo web extension

### PR DESCRIPTION
**Pull request by cristianpb**
I just did a small web extension for mopidy :)

### CODE REVIEW

**Comment by jodal** [comment]
Looks awesome with integrated Snapcast volume control :-)

I see that you've registered the Mopidy-Apollo name on PyPI, and with that have a very good claim to the name. However, there already exists a Mopidy web client, that has never been packaged as a Mopidy extension on PyPI, by the name [Apollo-Player](https://github.com/samcreate/Apollo-Player).

To avoid confusion with the old one, I'd recommend choosing another name before your extension is established with lots of users. Would you consider that?

**Comment by cristianpb** [comment]
Thanks for the feedback @jodal 
I didn't saw the name in PyPi so I thought it haven't been used before. 
But Ok, I think if I have to change the name it's better to do it now.

I was thinking on **Mopidy-Muse**, what do you think ?

**Comment by jodal** [comment]
Sounds good! I've never heard of anything with a similar name.

**Comment by cristianpb** [comment]
Ok, I'll change it, then I'll update this PR

**Comment by jodal** [comment]
Please include the images in this repo, so they don't stop working when something else changes. You can put them in `media/ext/`.

**Comment by jodal** [comment]
Thanks :-)

**Pull request merged**
